### ISSUE TITLE
安装说明建目录weights是不是少打了个s

### ISSUE THREAD

**Issue by mufenglyf** [jtydhr88/ComfyUI-Hunyuan3D-1-wrapper#3]
进到ComfyUI中该节点的文件夹创建weight文件夹，并在weights文件夹中创建hunyuanDiT文件夹
在此节点的目录中运行：
huggingface-cli download tencent/Hunyuan3D-1 --local-dir ./weights
和
huggingface-cli download Tencent-Hunyuan/HunyuanDiT-v1.1-Diffusers-Distilled --local-dir ./weights/hunyuanDiT

后面两个命令带了建目录的命令，执行容易混淆

**Comment by jtydhr88** [comment]
thanks, fixed
